<?php
use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help() for the module music search
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch($route_name) {
    case "help.page.music_search":
      $output = "";
      $output .= "<h3>" . t("About") . "<h3>"; //t() is a translate function instead of doing <h3> About <h3>
      $output .= "<p>" . t("This is the about page of the module music search") . "<p>";
      return $output;
    default:
  }
}
