<?php
namespace Drupal\music_search\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\music_search\SpotifySearchService;
use http\Env\Response;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class MusicSearchForm
 *
 * @package Drupal\music_search\Form
 */
class RadioButtonForm extends ConfigFormBase {
  /**
   * {@inheritDoc}
   */
  protected function getEditableConfigNames() {
    return ["music_search.search"];
  }

  /**
   * {@inheritDoc}
   */
  public function getFormId() {
    return "search_results";
  }

  /**
   * {@inheritDoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['radio_values'] = array(
      '#type' => 'radios',
      '#title' => t('Search Type'),
      '#options' => [
        t('Artist'),
        t('Album'),
        t('Track'),
      ]);
    $form["Continue"] = [
      "#type" => "submit",
      "#value" => "Continue"
    ];

    return $form;
  }

  /**
   * {@inheritDoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $radio_index = $form_state->getValue("radio_values");
    $radio_value = "";
    switch ($radio_index) {
      case 0:
        $radio_value = "artist";
        break;
      case 1:
        $radio_value = "album";
        break;
      case 2:
        $radio_value = "track";
    }
    $this->config("music_search.search")
      ->set("rad_val", $radio_value)
      ->save();
    $form_state->setRedirectUrl(Url::fromUri('internal:/music_search'));
    parent::submitForm($form, $form_state);
  }

  /**
   * {@inheritDoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    //Do later!!!!
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
