music_search.settings:
  type: config_object
  label: 'authentication config'
  mapping:
    spotify_client_id:
      type: text
      label: 'spotify_client_id'
    spotify_client_secret:
      type: text
      label: "spotify_client_secret"
